baseURL = 'https://www.joke.dad/'
languageCode = 'en-us'
title = 'joke.dad'
theme = "coming-soon"

[params]
    title = "joke.dad" 
    description = ""
    favicon = ""
    message = "COMING SOON!" 
    release = "" 
    background = "" 
